---

  - name: Añade key for jonathonf PPA para python3
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
      state: present

  - name: Añade jonathonf PPA para python3
    apt_repository:
      repo: deb http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main
      state: present

  - name: Instala Python 3.6
    apt:
      name: python3.6
      state: present
      update_cache: yes

  - name: Instala las dependencias del proyecto
    pip:
      state: latest
      requirements: /home/vagrant/Proyecto-cloud-computing/requirements.txt
      executable: pip3
