---

  - name: Instalar Python versión minimal.
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Añade repositorio para python.
    raw: (yum install -y https://centos7.iuscommunity.org/ius-release.rpm && yum update)

  - name: Añade repositorio para python.
    raw: yum install -y python36u python36u-libs python36u-devel python36u-pip

  - name: Instala paquetes necesarios con apt
    yum: package={{ item }}  state=latest

    with_items:
      - git

  - name: Instala easy_install
    yum:
      name: python-setuptools

  - name: Instala pip
    easy_install:
      name: pip
      state: latest

  - name: Actualiza pip
    pip: name=pip state=latest

  - name: Crea alias para python
    become: false
    lineinfile:
      path=~/.bashrc
      line="alias python='python3'"

  - name: Crea variable entorno locale
    become: false
    lineinfile:
      path=~/.bashrc
      line="export LANGUAGE='en_US.UTF-8'"

  - name: Crea variable entorno locale 2
    become: false
    lineinfile:
      path=~/.bashrc
      line="export LC_ALL='en_US.UTF-8'"

  - name: Instala pip3
    easy_install:
      name: pip3
      state: latest

  - name: Añade variable de la base de datos
    become: false
    lineinfile:
      path=~/.bashrc
      line="export MONGODB_USERS_KEY='mongodb://jmv74211:pwdcc18@ds151453.mlab.com:51453/heroku_5tv2mk96'"

  - name: Añade variable para codificar la clave de sesión de los usuarios
    become: false
    lineinfile:
      path=~/.bashrc
      line="export ENCODING_PHRASE='thisIsMyEncodingPhrase94'"

  - name: Descarga del repositorio
    become: true
    git:
      repo: https://github.com/jmv74211/Proyecto-cloud-computing.git
      dest: Proyecto-cloud-computing

  - name: Instala las dependencias del proyecto
    pip:
      state: latest
      requirements: /home/jmv74211/Proyecto-cloud-computing/requirements.txt
      executable: pip3
