language: python

python:
   - 3.5

install:
   pip install -r requirements.txt

branches:
  only:
  - master

script:
   - python src/test/test_funciones_login_registro.py
   - python src/test/test_servicio_login_registro.py
