language: python

python:
   - 3.6.7

# Instala las dependencias necesarias para la ejecución del proyecto
install:
   pip install -r requirements.txt

branches:
  only:
  - master

# Ejecución del conjunto de test unitarios y de integración
script:
   - python3 src/app/user_service/user_service.py &
   - python3 -W ignore src/test/test_user_service.py
   - pip3 install pymongo
   - python3 -W ignore src/test/test_functions_task_service.py
   - python3 -W ignore src/test/test_task_service.py
