language: python

python:
   - 3.5

# Instala las dependencias necesarias para la ejecución del proyecto
install:
   pip install -r requirements.txt

branches:
  only:
  - master

# Ejecución del conjunto de test unitarios y de integración
script:
   - python -W ignore src/test/test_funciones_login_registro.py
   - python -W ignore src/test/test_servicio_login_registro.py
   - python -W ignore src/test/test_functions_task_service.py
   - python -W ignore src/test/test_task_service.py
