---

  - name: Instalar Python versión minimal.
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Instala git
    apt:
      name: git
      state: present

  - name: Instala paquete locales
    apt:
      name: locales
      state: present

  - name: Instala paquetes build-essential
    apt:
      name: build-essential
      state: present

  - name: Instala paquetes language-pack-es
    apt:
      name: language-pack-es
      state: present

  - name: Instala python-pip
    apt:
      name: python-pip
      state: present

  - name: Actualiza pip
    pip: name=pip state=latest

  - name: Crea alias para python
    become: false
    lineinfile:
      path=~/.bashrc
      line="alias python='python3'"

  - name: Crea variable entorno locale
    become: false
    lineinfile:
      path=~/.bashrc
      line="export LANGUAGE='en_US.UTF-8'"

  - name: Crea variable entorno locale 2
    become: false
    lineinfile:
      path=~/.bashrc
      line="export LC_ALL='en_US.UTF-8'"

  - name: Instala pip3
    apt:
      package: python3-pip
      state: latest

  - name: Añade variable de conexión con la base de datos
    become: true
    lineinfile:
      path=~/.bashrc
      line="export MONGODB_USERS_KEY='{{ MONGODB_USERS_KEY }}'"

  - name: Añade variable para codificar la clave de sesión de los usuarios
    become: true
    lineinfile:
      path=~/.bashrc
      line="export ENCODING_PHRASE='{{ ENCODING_PHRASE }}'"

  - name: Descarga del repositorio
    become: true
    git:
      repo: https://github.com/jmv74211/Proyecto-cloud-computing.git
      dest: Proyecto-cloud-computing

  - name: Instala las dependencias del proyecto
    pip:
      state: latest
      requirements: /home/vagrant/Proyecto-cloud-computing/requirements_task-service.txt
      executable: pip3
